### ISSUE TITLE
`profile: postgres` is hard-coded in `features/003_hooks.feature`

### ISSUE THREAD

**Issue by jwills** [fishtown-analytics/dbt-integration-tests#3]
This line contains a hard-coded entry for `profile: postgres` which will make the integration tests fail if the argument value to `bin/run-with-profile <profile>` isn't, well, `postgres`.

https://github.com/fishtown-analytics/dbt-integration-tests/blob/master/features/003_hooks.feature#L61

From looking at the code and running it locally, I think that deleting that line is sufficient to fix the error so that other profile names will work as well.

**Comment by jwills** [comment]
PR for the same: https://github.com/fishtown-analytics/dbt-integration-tests/pull/4

**Comment by drewbanin** [comment]
FYI you can override the stated profile on the CLI by providing `--profile <profile name>` and `--target <target name>`, but I merged #4 because `postgres` wasn't a sane value to include there in the first place :)
